models:
  - huawei-noah/TinyBERT_General_4L_312D
  - albert-base-v2
  - distilbert-base-uncased
  - huawei-noah/TinyBERT_General_6L_768D
  - google/mobilebert-uncased

models_backend:
  - bert-base-uncased
  - roberta-base
  - microsoft/deberta-v3-base

training:
  epochs: 3
  batch_size: 32
  learning_rate: 2.0e-5
  max_length: 64
  threshold: tune_after_training
  seed: 42
  weight_decay: 0.01
  warmup_ratio: 0.1

training_backend:
  epochs: 3
  batch_size: 32
  learning_rate: 2.0e-5
  max_length: 256
  threshold: tune_after_training
  seed: 42
  weight_decay: 0.01
  warmup_ratio: 0.1

dataset:
  path: "../datasets/combined_urls_no_duplicated.csv"
  train_split: 0.70
  val_split: 0.15
  test_split: 0.15

dataset_backend:
  path: "../backend_training.csv"
  train_split: 0.70
  val_split: 0.15
  test_split: 0.15

hf_token: "very_secret_token"
hf_username: "OliverHeine/"
hf_train_version: "_train_v2"
hf_backend_train_version: "_train_v1"